### ISSUE TITLE
Suggestion: Change Title Color.

### ISSUE THREAD

**Issue by monsterboss14** [areeshalam/github-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #eaa021;
}
```
